name: algolia
version: 0.1.7-nullsafety.0
authors: 
  - Nayan Hathiwala (Knoxpo) <nhathiwala@knoxpo.com>
description: >
   Algolia is a pure dart SDK, wrapped around Algolia REST API for easy implementation for your Flutter or Dart projects.
homepage: https://github.com/knoxpo/dart_algolia

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  meta: ^1.3.0
  http: ^0.13.2
  uuid: ^3.0.4
  dio: ^4.0.0
  #dio_http_cache: ^0.2.11
  dio_http_cache:
    git:
      url: https://github.com/hurshi/dio-http-cache.git

dev_dependencies:
  test: ^1.17.2
